### ISSUE TITLE
Source of `Slack - Access Token` is wrong

### ISSUE THREAD

**Issue by eggplants** [odomojuli/regextokens#8]
`https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}` is meaningless.

Maybe:
<https://github.com/trufflesecurity/truffleHog/blob/0f223225d6efc8c64504d9381eececb06b14c0e6/scripts/searchOrg.py#L25>

**Comment by odomojuli** [comment]
It appears Slack has deprecated legacy access token implementation.

> [Access Tokens](https://api.slack.com/authentication/token-types)

There are now prefixes supported for `bot`, `user`.

Bot token strings begin with ```xoxb-```
User token strings begin with ```xoxp-```

Configuration tokens include a rotating refresh token.
[App Configuration Token](https://api.slack.com/authentication/config-tokens)

`workspace` has been deprecated officially as of August 2021.
> [Workspace apps will retire in August 2021](https://api.slack.com/changelog/2021-03-workspace-apps-to-retire-in-august-2021)

I would prefer not to cite another repository's entry without an original source.
In this case, the now outdated source for this entry brought attention to this recent change in implementation.

Thank you!

**Comment by eggplants** [comment]
I mean the link of `Slack - Access Token`'s `Source` column is maybe wrong. Where did you cite this regex from?

**Comment by odomojuli** [comment]
Oh I see what you mean.
Nice catch.
I understand now how that "source" is vague and confusing.

I believe I meant to refer to this legacy source:
> [Using OAuth 2.0](https://api.slack.com/legacy/oauth) _Note: deprecated._
This pattern is pulled from the Webhook URL, which you correctly pointed out does not validate to any URL.
 `T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}`

The source is mislabeled, and should be removed and updated anyways to the new v2 implementation.

**Comment by eggplants** [comment]
Please close this issue when you fix it.

**Comment by odomojuli** [comment]
This issue has been marked as resolved.
